name: Publish App
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "app/**"
      - ".github/workflows/app.yaml"

env:
  API_URL: https://api.davidvargas.me
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  IS_PRODUCTION: 1
  ORIGIN: https://app.davidvargas.me
  STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: deploy
        run: npm run deploy
